packages:
  - name: rugs
    actions:
      - name: rug
        runtime: 'python:default'
        limits:
          timeout: 9000
  - name: sample
    actions:
      - name: hello
        runtime: 'python:default'
        limits:
          timeout: 9000