packages:
  - name: rugs
    environment:
      CLIENT_ID: "${CLIENT_ID}"
      CLIENT_SECRET: "${CLIENT_SECRET}"
      ACCESS_TOKEN: "${ACCESS_TOKEN}"
      REFRESH_TOKEN: "${REFRESH_TOKEN}"
      EXPIRES_IN: ${"EXPIRES_IN}"
    actions:
      - name: rug
        runtime: 'python:default'
        limits:
          timeout: 5000
  - name: sample
    actions:
      - name: hello
        runtime: 'python:default'
        limits:
          timeout: 5000